version: '3.3'
services:
  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    command: python skindetector.py
    image: cv-goniometer:dev
    devices:
      - /dev/video0:/dev/video0
    environment:
      DISPLAY: unix${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

